variables:
    TUTOR_PLUGIN: indigo
    TUTOR_PYPI_PACKAGE: tutor-indigo
    TUTOR_BUILD_IMAGE: openedx
    OPENEDX_RELEASE: palm
    GITHUB_REPO: overhangio/tutor-indigo

include:
  - project: 'community/tutor-ci'
    file: 'plugin-gitlab-ci.yml'
